# Docker Compose for Development

services:
  # DeliverGaz Backend API (Development)
  delivergaz-backend-dev:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: delivergaz-api-dev
    ports:
      - "${PORT:-4000}:4000"
      - "9229:9229"  # Debug port
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/${DB_NAME:-delivergaz}
      - DB_NAME=${DB_NAME:-delivergaz}
      - JWT_SECRET=${JWT_SECRET:-dev_jwt_secret_key}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-7d}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET:-dev_refresh_secret_key}
      - JWT_REFRESH_EXPIRES_IN=${JWT_REFRESH_EXPIRES_IN:-30d}
      - BCRYPT_SALT_ROUNDS=${BCRYPT_SALT_ROUNDS:-10}
      - UPLOAD_PATH=uploads/
      - MAX_FILE_SIZE=${MAX_FILE_SIZE:-5242880}
      - ALLOWED_FILE_TYPES=${ALLOWED_FILE_TYPES:-jpg,jpeg,png,gif,webp}
      - CORS_ORIGIN=${CORS_ORIGIN:-*}
      - RATE_LIMIT_WINDOW=${RATE_LIMIT_WINDOW:-15}
      - RATE_LIMIT_MAX_REQUESTS=${RATE_LIMIT_MAX_REQUESTS:-1000}
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    networks:
      - delivergaz-dev-network
    restart: unless-stopped
    command: npm run dev

  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: delivergaz-mongodb-dev
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=${DB_NAME:-delivergaz}
    volumes:
      - mongodb_dev_data:/data/db
      - mongodb_dev_config:/data/configdb
    networks:
      - delivergaz-dev-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # MongoDB Express (Web-based MongoDB admin interface)
  mongo-express:
    image: mongo-express:1.0.2
    container_name: delivergaz-mongo-express-dev
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - delivergaz-dev-network
    restart: unless-stopped

# Networks
networks:
  delivergaz-dev-network:
    driver: bridge
    name: delivergaz-dev-network

# Volumes for persistent data
volumes:
  mongodb_dev_data:
    name: delivergaz_mongodb_dev_data
  mongodb_dev_config:
    name: delivergaz_mongodb_dev_config