name: Docker build and push (GHCR)
description: Build and push a Docker image using Buildx to GHCR
inputs:
  context:
    description: Build context path
    required: false
    default: ./backend
  file:
    description: Dockerfile path
    required: false
    default: ./backend/Dockerfile
  tags:
    description: Image tags (newline separated)
    required: true
  registry:
    description: Container registry
    required: false
    default: ghcr.io
  username:
    description: Registry username
    required: false
    default: ${{ github.actor }}
  password:
    description: Registry password or token
    required: false
    default: ${{ github.token }}
runs:
  using: composite
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.file }}
        push: true
        tags: ${{ inputs.tags }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
