name: Docker Build & Push (composite)
description: Build and push Docker image using Buildx
inputs:
  context:
    description: Build context
    required: true
  file:
    description: Dockerfile path
    required: true
  tags:
    description: Image tags (newline-separated)
    required: true
  registry:
    description: Container registry hostname (e.g., ghcr.io)
    required: true
  username:
    description: Registry username
    required: true
  password:
    description: Registry password/token
    required: true
runs:
  using: composite
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.file }}
        push: true
        tags: ${{ inputs.tags }}
