name: Backend CI

on:
  pull_request:
    paths:
      - backend/**
      - pipelines/backend-ci/**
      - .github/workflows/backend-ci.yml
  workflow_dispatch:

concurrency:
  group: backend-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  backend:
    name: Lint, build and test backend
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:6
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --quiet --eval 'db.adminCommand(\"ping\")'" 
          --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Backend CI pipeline
        uses: ./pipelines/backend-ci
        with:
          workdir: backend
          node-version: '18'
          cache-lock-path: backend/package-lock.json
          mongodb-uri: mongodb://127.0.0.1:27017/delivergaz_test
          db-name: delivergaz_test