name: Backend CI

on:
  push:
    branches: ["**"]
    paths:
      - backend/**
      - .github/workflows/backend-ci.yml
  pull_request:
    paths:
      - backend/**
      - .github/workflows/backend-ci.yml

jobs:
  backend:
    name: Lint, build and test backend
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:6
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --quiet --eval 'db.adminCommand(\"ping\")'" \
          --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Install dependencies
        run: |
          cd backend
          npm ci

      - name: Run ESLint
        run: |
          cd backend
          npm run lint

      - name: Build TypeScript
        run: |
          cd backend
          npm run build

      - name: Run tests
        run: |
          cd backend
          npm test
        env:
          NODE_ENV: test
          MONGODB_TEST_URI: mongodb://localhost:27017/delivergaz_test
          JWT_SECRET: test-jwt-secret-for-testing-only