name: Frontend CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  frontend:
    name: Analyze and Test (frontend)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Frontend CI pipeline
        uses: ./pipelines/frontend-ci
        with:
          workdir: frontend
          flutter-channel: stable
          workdir: frontend
          flutter-channel: stable
