name: Frontend CI

on:
  push:
    branches: ["**"]
    paths:
      - frontend/**
      - .github/workflows/frontend-ci.yml
  pull_request:
    paths:
      - frontend/**
      - .github/workflows/frontend-ci.yml

jobs:
  frontend:
    name: Analyze and test Flutter frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'
          cache: true

      - name: Install dependencies
        run: |
          cd frontend
          flutter pub get

      - name: Verify Flutter installation
        run: flutter doctor -v

      - name: Run Flutter analyzer
        run: |
          cd frontend
          flutter analyze --fatal-infos

      - name: Run Flutter tests
        run: |
          cd frontend
          flutter test --coverage