name: Frontend CI

on:
  push:
    branches: ["**"]
    paths:
      - frontend/**
      - pipelines/frontend-ci/**
      - .github/workflows/frontend-ci.yml
  pull_request:
    paths:
      - frontend/**
      - pipelines/frontend-ci/**
      - .github/workflows/frontend-ci.yml

jobs:
  frontend:
    name: Analyze and test Flutter frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Frontend CI (composite)
        uses: ./pipelines/frontend-ci
        with:
          workdir: frontend
          flutter-channel: stable
