name: Frontend CI

on:
  push:
    branches: ["**"]
    paths:
      - frontend/**
      - pipelines/frontend-ci/**
      - .github/workflows/frontend-ci.yml
  pull_request:
    paths:
      - frontend/**
      - pipelines/frontend-ci/**
      - .github/workflows/frontend-ci.yml

jobs:
  frontend:
    name: Analyze and test Flutter frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Frontend CI (composite)
        uses: ./pipelines/frontend-ci
        with:
          workdir: frontend
          flutter-channel: stable
name: Frontend CI (composite)
description: Analyze and test the Flutter frontend
inputs:
  workdir:
    description: Working directory for frontend
    required: false
    default: frontend
  flutter-channel:
    description: Flutter channel
    required: false
    default: stable
runs:
  using: composite
  steps:
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: ${{ inputs['flutter-channel'] }}

    - name: Flutter pub get
      shell: bash
      working-directory: ${{ inputs.workdir }}
      run: flutter pub get

    - name: Flutter analyze
      shell: bash
      working-directory: ${{ inputs.workdir }}
      run: flutter analyze

    - name: Flutter tests
      shell: bash
      working-directory: ${{ inputs.workdir }}
      run: flutter test -r expanded