name: Release

on:
  push:
    branches: [ stage ]
  workflow_dispatch:

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-push-backend:
    name: Build and push backend image to GHCR
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show workflow context
        shell: bash
        run: |
          echo "repo: ${{ github.repository }}"
          echo "actor: ${{ github.actor }}"
          echo "ref: ${{ github.ref }} (name: ${{ github.ref_name }})"
          echo "sha: ${{ github.sha }}"
          echo "event: ${{ github.event_name }}"
          echo "intended image tags: ghcr.io/${{ github.repository_owner }}/delivergaz-backend:latest, :${{ github.sha }}"
          if [[ -n "${{ secrets.API_BASE_URL_PROD }}" ]]; then echo "API_BASE_URL_PROD: set"; else echo "API_BASE_URL_PROD: not set"; fi

      - name: Setup Flutter (stable)
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter version
        run: flutter --version

      - name: Frontend - flutter pub get
        working-directory: frontend
        run: flutter pub get

      - name: Frontend - build web (release)
        working-directory: frontend
        run: flutter build web --release --dart-define=API_BASE_URL=${{ secrets.API_BASE_URL_PROD }}

      - name: Publish web build to backend/public
        shell: bash
        run: |
          rm -rf backend/public && mkdir -p backend/public
          cp -a frontend/build/web/. backend/public/
          echo "backend/public file count:" && find backend/public -type f | wc -l
          echo "backend/public top-level contents:" && ls -la backend/public | sed -n '1,50p'

      - name: Build and push Backend image
        uses: ./pipelines/docker-build-push
        with:
          context: ./backend
          file: ./backend/Dockerfile
          tags: |
            ghcr.io/${{ github.repository_owner }}/delivergaz-backend:latest
            ghcr.io/${{ github.repository_owner }}/delivergaz-backend:${{ github.sha }}
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Backend image
        uses: ./pipelines/docker-build-push
        with:
          context: ./backend
          file: ./backend/Dockerfile
          tags: |
            ghcr.io/${{ github.repository_owner }}/delivergaz-backend:latest
            ghcr.io/${{ github.repository_owner }}/delivergaz-backend:${{ github.sha }}
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    needs: build-and-push-backend
    if: ${{ github.ref == 'refs/heads/stage' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Resolve SSH port
        id: port
        shell: bash
        run: |
          if [[ -n "${{ secrets.EC2_PORT }}" ]]; then
            echo "port=${{ secrets.EC2_PORT }}" >> "$GITHUB_OUTPUT"
          else
            echo "port=22" >> "$GITHUB_OUTPUT"
          fi

      - name: Show deployment parameters
        shell: bash
        run: |
          echo "ref: ${{ github.ref }} (name: ${{ github.ref_name }})"
          echo "image: ghcr.io/${{ github.repository_owner }}/delivergaz-backend:latest"
          echo "container port mapping: 3000:3000"
          echo "ssh port (effective): ${{ steps.port.outputs.port }}"
          if [[ -n "${{ secrets.EC2_HOST }}" ]]; then echo "EC2_HOST: set"; else echo "EC2_HOST: not set"; fi
          if [[ -n "${{ secrets.EC2_USER }}" ]]; then echo "EC2_USER: set"; else echo "EC2_USER: not set"; fi
          if [[ -n "${{ secrets.EC2_SSH_KEY }}" ]]; then echo "EC2_SSH_KEY: set"; else echo "EC2_SSH_KEY: not set"; fi
          if [[ -n "${{ secrets.EC2_PORT }}" ]]; then echo "EC2_PORT: set"; else echo "EC2_PORT: not set (default 22)"; fi
          if [[ -n "${{ secrets.GHCR_USERNAME }}" ]]; then echo "GHCR_USERNAME: set"; else echo "GHCR_USERNAME: not set"; fi
          if [[ -n "${{ secrets.GHCR_PAT }}" ]]; then echo "GHCR_PAT: set"; else echo "GHCR_PAT: not set"; fi
          echo "remote env-file: /opt/delivergaz/backend/.env"

      - name: Deploy to EC2
        uses: ./pipelines/ec2-ssh-deploy
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_PORT || '22' }}
          image: ghcr.io/${{ github.repository_owner }}/delivergaz-backend:latest
          ghcr-username: ${{ secrets.GHCR_USERNAME }}
          ghcr-pat: ${{ secrets.GHCR_PAT }}
          app-name: delivergaz-api
          host-port: '3000'
          container-port: '3000'
          env-file: /opt/delivergaz/backend/.env
          network: delivergaz-network