name: Backend CI (composite)
description: Lint, build and test the backend with Node.js
inputs:
  workdir:
    description: Working directory for backend
    required: false
    default: backend
  node-version:
    description: Node.js version
    required: false
    default: '18'
  cache-lock-path:
    description: Path to package-lock.json for caching
    required: false
    default: backend/package-lock.json
  mongodb-uri:
    description: MongoDB URI for tests
    required: false
    default: mongodb://127.0.0.1:27017/delivergaz_test
  db-name:
    description: Database name for tests
    required: false
    default: delivergaz_test
runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs['node-version'] }}
        cache: npm
        cache-dependency-path: ${{ inputs['cache-lock-path'] }}

    - name: Install dependencies
      shell: bash
      working-directory: ${{ inputs.workdir }}
      run: |
        if [ -f package-lock.json ]; then npm ci; else npm install; fi

    - name: Lint
      shell: bash
      working-directory: ${{ inputs.workdir }}
      run: npm run lint

    - name: TypeScript build
      shell: bash
      working-directory: ${{ inputs.workdir }}
      run: npm run build

    - name: Run tests
      shell: bash
      working-directory: ${{ inputs.workdir }}
      env:
        NODE_ENV: test
        MONGODB_URI: ${{ inputs['mongodb-uri'] }}
        DB_NAME: ${{ inputs['db-name'] }}
      run: npm test -- --passWithNoTests
